spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_SSO_CLIENT}
            client-secret: ${GITHUB_SSO_SECRET}
  thymeleaf:
    cache: false
    
server:
  port: ${APP_PORT:8082}
  servlet: 
    context-path: /lsso-client
    
logging: 
  level: 
    org.springframework: INFO
        